spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/swiftyticketing
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                

twilio:
    AccountSID: ${TW_SID}
    AuthToken: ${TW_AUTHTOKEN}
    phoneNumber: ${TW_PHONENUMBER}
token:
    signing:
        key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
#logging:
#    level:
#        org.springframework.security: TRACE
